version: '3.7'

services:
  currency-exchange:
    image: jere/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.service-url.default-zone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411
      rabbit_uri: amqp://guest:guest@rabbitmq:5672
      spring_rabbitmq_host: rabbitmq
      spring_zipkin_sender_type: rabbit

  currency-conversion:
    image: jere/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.service-url.default-zone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411
      rabbit_uri: amqp://guest:guest@rabbitmq:5672
      spring_rabbitmq_host: rabbitmq
      spring_zipkin_sender_type: rabbit

  api-gateway:
    image: jere/mmv2-api-gateway:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      eureka.client.service-url.default-zone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411
      rabbit_uri: amqp://guest:guest@rabbitmq:5672
      spring_rabbitmq_host: rabbitmq
      spring_zipkin_sender_type: rabbit

  naming-server:
    image: jere/mmv2-naming-server:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    deploy:
      resources:
        limits:
          memory: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: always #Restart if there is a problem starting up

  rabbitmq:
    image: rabbitmq:3.11.0-management
    deploy:
      resources:
        limits:
          memory: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network

networks:
  currency-network: